// triviaBank.js — Quick Trivia question packs

export const TRIVIA_CATEGORIES = {
  movies: {
    label: "Movies", emoji: "🎬",
    questions: [
      { q: "Who directed the blockbuster 'RRR' (2022)?", options: ["Trivikram Srinivas", "S. S. Rajamouli", "Sukumar", "Boyapati Srinu"], answer: 1 },
      { q: "Which Telugu film features the song 'Naatu Naatu' that won the Oscar?", options: ["Pushpa", "Baahubali 2", "RRR", "Akhanda"], answer: 2 },
      { q: "'Baahubali: The Beginning' was released in which year?", options: ["2013", "2014", "2015", "2016"], answer: 2 },
      { q: "Who plays Amarendra Baahubali in the Baahubali franchise?", options: ["Ram Charan", "Jr NTR", "Prabhas", "Rana Daggubati"], answer: 2 },
      { q: "Which actor is known as 'Mega Star' in Telugu cinema?", options: ["Pawan Kalyan", "Chiranjeevi", "Venkatesh", "Nagarjuna"], answer: 1 },
      { q: "Who directed 'Pushpa: The Rise'?", options: ["S. S. Rajamouli", "Trivikram Srinivas", "Sukumar", "Harish Shankar"], answer: 2 },
      { q: "'Arya' (2004) starred which Telugu actor?", options: ["Ram Charan", "Allu Arjun", "Jr NTR", "Mahesh Babu"], answer: 1 },
      { q: "What is the name of Allu Arjun's character in 'Pushpa'?", options: ["Pushpa Raj", "Arya", "Deva", "Samba"], answer: 0 },
      { q: "Which film has the iconic dialogue 'Kattappa ne Baahubali ko kyun maara'?", options: ["Magadheera", "Baahubali: The Beginning", "Baahubali 2: The Conclusion", "RRR"], answer: 1 },
      { q: "Who composed the music for 'Baahubali'?", options: ["A. R. Rahman", "Devi Sri Prasad", "M. M. Keeravani", "Thaman S"], answer: 2 },
      { q: "Which actor is known as 'Prince' in Telugu cinema?", options: ["Allu Arjun", "Ram Charan", "Mahesh Babu", "Jr NTR"], answer: 2 },
      { q: "The movie 'Magadheera' (2009) starred which actor in a dual role?", options: ["Prabhas", "Mahesh Babu", "Ram Charan", "Jr NTR"], answer: 2 },
      { q: "Which South Indian director made 'Enthiran' (Robot)?", options: ["Mani Ratnam", "S. Shankar", "K. S. Ravikumar", "Vijay Milton"], answer: 1 },
      { q: "'KGF: Chapter 1' is primarily in which language?", options: ["Telugu", "Tamil", "Kannada", "Malayalam"], answer: 2 },
      { q: "Who played the lead in 'Vikram Vedha' (original Tamil, 2017)?", options: ["Vijay Sethupathi & R. Madhavan", "Suriya & Vijay", "Dhanush & Sivakarthikeyan", "Ajith & Vijay"], answer: 0 },
      { q: "Which Telugu movie features the 'Butta Bomma' song?", options: ["Ala Vaikunthapurramuloo", "Sarileru Neekevvaru", "Geetha Govindam", "Arya 2"], answer: 0 },
      { q: "Jr NTR's character in 'RRR' is based on which freedom fighter?", options: ["Alluri Sitarama Raju", "Komaram Bheem", "Bhagat Singh", "Subhash Chandra Bose"], answer: 1 },
      { q: "Ram Charan's character in 'RRR' is based on which freedom fighter?", options: ["Komaram Bheem", "Tipu Sultan", "Alluri Sitarama Raju", "Bhagat Singh"], answer: 2 },
      { q: "Who is known as the 'Rebel Star' of Telugu cinema?", options: ["Prabhas", "Balakrishna", "Krishnam Raju", "Chiranjeevi"], answer: 0 },
      { q: "Which 2023 Telugu film starred Mahesh Babu directed by Trivikram?", options: ["Guntur Kaaram", "SSMB28", "Maharshi 2", "Bharat Ane Nenu 2"], answer: 0 },
    ],
  },
  anime: {
    label: "Anime", emoji: "⛩️",
    questions: [
      { q: "What is the name of the pirate crew in 'One Piece'?", options: ["Red Hair Pirates", "Straw Hat Pirates", "Whitebeard Pirates", "Heart Pirates"], answer: 1 },
      { q: "In 'Naruto', what village is Naruto from?", options: ["Sand", "Mist", "Leaf", "Stone"], answer: 2 },
      { q: "What is Light Yagami's weapon of choice in 'Death Note'?", options: ["A sword", "A gun", "The Death Note", "Poison"], answer: 2 },
      { q: "Which anime features Titans attacking humanity?", options: ["Attack on Titan", "Demon Slayer", "Jujutsu Kaisen", "Tokyo Ghoul"], answer: 0 },
      { q: "What is the main character's dream job in 'My Hero Academia'?", options: ["Doctor", "Hero", "Teacher", "Police Officer"], answer: 1 },
      { q: "Studio Ghibli's 'Spirited Away' is directed by whom?", options: ["Makoto Shinkai", "Hayao Miyazaki", "Mamoru Hosoda", "Satoshi Kon"], answer: 1 },
      { q: "What fruit gives Luffy his rubber powers?", options: ["Gum-Gum Fruit", "Flame-Flame Fruit", "Ice-Ice Fruit", "Bomb-Bomb Fruit"], answer: 0 },
      { q: "Who is the main protagonist in 'Demon Slayer'?", options: ["Zenitsu", "Inosuke", "Tanjiro", "Giyu"], answer: 2 },
      { q: "In 'Dragon Ball Z', what transformation is achieved when a Saiyan's hair turns golden?", options: ["Kaioken", "Super Saiyan", "Ultra Instinct", "Oozaru"], answer: 1 },
      { q: "What is the name of the survey corps in 'Attack on Titan'?", options: ["Scout Regiment", "Garrison Regiment", "Military Police", "Titan Corps"], answer: 0 },
      { q: "Which anime is set in the world of Alchemy and Philosopher's Stones?", options: ["Bleach", "Naruto", "Fullmetal Alchemist", "Blue Exorcist"], answer: 2 },
      { q: "In 'Jujutsu Kaisen', who is Yuji Itadori's cursed spirit vessel?", options: ["Gojo Satoru", "Sukuna", "Nanami", "Megumi"], answer: 1 },
      { q: "What is the sport played in 'Haikyuu!!'?", options: ["Basketball", "Football", "Volleyball", "Badminton"], answer: 2 },
      { q: "Which character says 'Believe it!' (Dattebayo) in Naruto?", options: ["Sasuke", "Naruto", "Rock Lee", "Kakashi"], answer: 1 },
      { q: "In 'One Punch Man', what is Saitama's limit for push-ups in his training?", options: ["50", "75", "100", "200"], answer: 2 },
      { q: "Which anime features the 'Ackerman' clan?", options: ["Demon Slayer", "Attack on Titan", "One Piece", "Bleach"], answer: 1 },
      { q: "Who trained Goku in 'Dragon Ball Z'?", options: ["King Kai", "Vegeta", "Master Roshi", "Piccolo"], answer: 0 },
      { q: "In 'Sword Art Online', what game are players trapped in first?", options: ["Alfheim Online", "Gun Gale Online", "Sword Art Online", "Project Alicization"], answer: 2 },
      { q: "What does 'Senpai' mean in Japanese?", options: ["Teacher", "Friend", "Upperclassman/Senior", "Enemy"], answer: 2 },
      { q: "Which anime's protagonist has the power of the 'Shinigami' (Death God)?", options: ["Bleach", "Death Note", "Soul Eater", "Black Clover"], answer: 0 },
    ],
  },
  cricket: {
    label: "Cricket", emoji: "🏏",
    questions: [
      { q: "How many players are on a cricket team?", options: ["9", "10", "11", "12"], answer: 2 },
      { q: "Which country won the 2023 Cricket World Cup?", options: ["India", "Australia", "England", "New Zealand"], answer: 1 },
      { q: "What is a perfect over called when no runs are scored?", options: ["Golden over", "Maiden over", "Silent over", "Dot over"], answer: 1 },
      { q: "Who holds the record for most international centuries?", options: ["Virat Kohli", "Ricky Ponting", "Sachin Tendulkar", "Kumar Sangakkara"], answer: 2 },
      { q: "How many runs is a 'six' worth?", options: ["4", "5", "6", "7"], answer: 2 },
      { q: "Which format has exactly 20 overs per side?", options: ["Test", "ODI", "T20", "T10"], answer: 2 },
      { q: "How many wickets make up a 'hat-trick'?", options: ["2", "3", "4", "5"], answer: 1 },
      { q: "What is the term for a ball delivered illegally over waist height?", options: ["No ball", "Wide", "Beamer", "Bouncer"], answer: 2 },
      { q: "Which Indian city's team won the IPL most times?", options: ["Delhi", "Kolkata", "Chennai", "Mumbai"], answer: 3 },
      { q: "What is the highest individual score in a Test match?", options: ["374", "400", "401", "375"], answer: 2 },
      { q: "Who was the first batsman to score 10,000 runs in Test cricket?", options: ["Brian Lara", "Sunil Gavaskar", "Allan Border", "Vivian Richards"], answer: 1 },
      { q: "Which bowler has taken the most wickets in Test cricket history?", options: ["Glenn McGrath", "Shane Warne", "Muttiah Muralitharan", "James Anderson"], answer: 2 },
      { q: "What does 'LBW' stand for?", options: ["Leg Before Wicket", "Low Ball Wide", "Left Behind Wicket", "Long Ball Win"], answer: 0 },
      { q: "In which city is Eden Gardens cricket stadium located?", options: ["Mumbai", "Delhi", "Kolkata", "Chennai"], answer: 2 },
      { q: "Who captained India in the 2011 Cricket World Cup win?", options: ["Sourav Ganguly", "Virat Kohli", "MS Dhoni", "Anil Kumble"], answer: 2 },
      { q: "How many balls are there in a standard over?", options: ["4", "5", "6", "8"], answer: 2 },
      { q: "What shot is played when the ball is hit behind square on the leg side?", options: ["Sweep", "Pull", "Glance / Flick", "Cut"], answer: 2 },
      { q: "Virat Kohli reached 50 ODI centuries in which year?", options: ["2022", "2023", "2024", "2025"], answer: 1 },
      { q: "Who was the first Indian to score a double century in ODIs?", options: ["Virat Kohli", "Sachin Tendulkar", "Rohit Sharma", "MS Dhoni"], answer: 1 },
      { q: "Which country introduced the Ashes Test series?", options: ["India vs Pakistan", "England vs Australia", "West Indies vs England", "South Africa vs Australia"], answer: 1 },
    ],
  },
  football: {
    label: "Football", emoji: "⚽",
    questions: [
      { q: "Which country has won the most FIFA World Cups?", options: ["Germany", "Argentina", "Brazil", "Italy"], answer: 2 },
      { q: "How long is a standard football match?", options: ["80 minutes", "90 minutes", "100 minutes", "120 minutes"], answer: 1 },
      { q: "Who is nicknamed 'CR7'?", options: ["Lionel Messi", "Cristiano Ronaldo", "Neymar Jr", "Kylian Mbappe"], answer: 1 },
      { q: "Which club has won the most UEFA Champions League titles?", options: ["Barcelona", "AC Milan", "Bayern Munich", "Real Madrid"], answer: 3 },
      { q: "What's the maximum number of substitutions in a standard match (post-2020)?", options: ["3", "4", "5", "6"], answer: 2 },
      { q: "Which player won the 2022 World Cup Golden Boot?", options: ["Messi", "Mbappe", "Ronaldo", "Griezmann"], answer: 1 },
      { q: "Who won the 2022 FIFA World Cup?", options: ["France", "Croatia", "Brazil", "Argentina"], answer: 3 },
      { q: "Which club did Lionel Messi join in 2023 (MLS)?", options: ["LA Galaxy", "New York City FC", "Inter Miami", "Atlanta United"], answer: 2 },
      { q: "The 'Offside Rule' in football means a player must have at least how many opponents between them and the goal?", options: ["1", "2", "3", "0"], answer: 1 },
      { q: "Which country hosted the 2018 FIFA World Cup?", options: ["Qatar", "Brazil", "Russia", "South Africa"], answer: 2 },
      { q: "Who is the all-time top scorer in Champions League history?", options: ["Lionel Messi", "Raul Gonzalez", "Cristiano Ronaldo", "Robert Lewandowski"], answer: 2 },
      { q: "The 'Bicycle Kick' is also known as?", options: ["Diving header", "Scissor kick / Overhead kick", "Volley", "Chip shot"], answer: 1 },
      { q: "How many players form a team on the pitch including the goalkeeper?", options: ["10", "11", "12", "9"], answer: 1 },
      { q: "What trophy is awarded to the top scorer in the English Premier League each season?", options: ["Golden Boot", "Golden Glove", "Golden Ball", "Silver Boot"], answer: 0 },
      { q: "Neymar Jr started his career at which club?", options: ["Barcelona", "PSG", "Santos FC", "Flamengo"], answer: 2 },
      { q: "Which nation won the first-ever FIFA World Cup in 1930?", options: ["Brazil", "Argentina", "Uruguay", "Italy"], answer: 2 },
      { q: "What is a 'brace' in football?", options: ["An own goal", "A yellow card", "Two goals in one game by one player", "A penalty miss"], answer: 2 },
      { q: "Which country will host the 2026 FIFA World Cup?", options: ["Australia & NZ", "USA, Canada & Mexico", "Spain, Portugal & Morocco", "Saudi Arabia"], answer: 1 },
    ],
  },
  general: {
    label: "General Knowledge", emoji: "🌍",
    questions: [
      { q: "What is the largest planet in our solar system?", options: ["Earth", "Saturn", "Jupiter", "Neptune"], answer: 2 },
      { q: "Which gas do plants primarily absorb?", options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], answer: 2 },
      { q: "What is the capital of Japan?", options: ["Seoul", "Beijing", "Tokyo", "Bangkok"], answer: 2 },
      { q: "How many continents are there?", options: ["5", "6", "7", "8"], answer: 2 },
      { q: "What is the smallest prime number?", options: ["0", "1", "2", "3"], answer: 2 },
      { q: "Which organ pumps blood through the body?", options: ["Lungs", "Brain", "Liver", "Heart"], answer: 3 },
      { q: "What's the chemical symbol for gold?", options: ["Go", "Gd", "Au", "Ag"], answer: 2 },
      { q: "What is the longest river in the world?", options: ["Amazon", "Yangtze", "Mississippi", "Nile"], answer: 3 },
      { q: "How many bones are in the adult human body?", options: ["196", "206", "216", "226"], answer: 1 },
      { q: "Which planet is known as the Red Planet?", options: ["Venus", "Jupiter", "Mars", "Saturn"], answer: 2 },
      { q: "What is the hardest natural substance on Earth?", options: ["Gold", "Iron", "Diamond", "Platinum"], answer: 2 },
      { q: "Which country is the largest by land area?", options: ["USA", "Canada", "China", "Russia"], answer: 3 },
      { q: "How many sides does a hexagon have?", options: ["5", "6", "7", "8"], answer: 1 },
      { q: "What language has the most native speakers in the world?", options: ["English", "Spanish", "Hindi", "Mandarin Chinese"], answer: 3 },
      { q: "Who painted the Mona Lisa?", options: ["Michelangelo", "Raphael", "Leonardo da Vinci", "Caravaggio"], answer: 2 },
      { q: "What is the speed of light (approximately)?", options: ["100,000 km/s", "200,000 km/s", "300,000 km/s", "400,000 km/s"], answer: 2 },
      { q: "Which element has the atomic number 1?", options: ["Helium", "Oxygen", "Carbon", "Hydrogen"], answer: 3 },
      { q: "In which year did World War II end?", options: ["1943", "1944", "1945", "1946"], answer: 2 },
      { q: "What is the capital of India?", options: ["Mumbai", "Kolkata", "New Delhi", "Chennai"], answer: 2 },
      { q: "Which ocean is the largest on Earth?", options: ["Atlantic", "Indian", "Arctic", "Pacific"], answer: 3 },
    ],
  },
  coding: {
    label: "Coding", emoji: "💻",
    questions: [
      { q: "What does 'HTML' stand for?", options: ["HyperText Markup Language", "HighText Machine Language", "HyperTransfer Markup Language", "Home Tool Markup Language"], answer: 0 },
      { q: "Which symbol is used for comments in JavaScript (single line)?", options: ["#", "//", "<!--", "**"], answer: 1 },
      { q: "What does 'CSS' control on a webpage?", options: ["Logic", "Structure", "Styling", "Database"], answer: 2 },
      { q: "Which company developed React?", options: ["Google", "Meta", "Microsoft", "Amazon"], answer: 1 },
      { q: "What does 'API' stand for?", options: ["Application Programming Interface", "Automated Program Instruction", "App Process Integration", "Applied Programming Index"], answer: 0 },
      { q: "In Python, what symbol starts a comment?", options: ["//", "#", "--", "/*"], answer: 1 },
      { q: "What does 'SQL' primarily work with?", options: ["Styling", "Databases", "Animations", "Networking"], answer: 1 },
      { q: "Which data structure follows the LIFO principle?", options: ["Queue", "Stack", "Array", "Linked List"], answer: 1 },
      { q: "What does 'DOM' stand for in web development?", options: ["Document Object Model", "Data Output Module", "Digital Oriented Map", "Document Order Mode"], answer: 0 },
      { q: "Which language is primarily used for Android app development?", options: ["Swift", "Python", "Kotlin / Java", "C#"], answer: 2 },
      { q: "What does 'Git' help developers do?", options: ["Design UI", "Version control / Track code changes", "Deploy servers", "Write tests"], answer: 1 },
      { q: "What is the output of 2 ** 10 in Python?", options: ["20", "512", "1024", "100"], answer: 2 },
      { q: "Which HTTP status code means 'Not Found'?", options: ["200", "301", "404", "500"], answer: 2 },
      { q: "What is the main purpose of a CDN?", options: ["Store databases", "Deliver content faster via distributed servers", "Compress images", "Encrypt passwords"], answer: 1 },
      { q: "Which sorting algorithm has the best average-case time complexity?", options: ["Bubble Sort", "Selection Sort", "Quick Sort / Merge Sort", "Insertion Sort"], answer: 2 },
      { q: "In JavaScript, what does '===' do differently from '=='?", options: ["Nothing different", "Checks value only", "Checks both value and type", "Checks type only"], answer: 2 },
      { q: "What does 'npm' stand for?", options: ["Node Package Module", "Node Package Manager", "New Program Module", "Node Program Manager"], answer: 1 },
      { q: "Which company developed the TypeScript language?", options: ["Google", "Meta", "Microsoft", "Apple"], answer: 2 },
      { q: "What is 'Big O' notation used to describe?", options: ["Bug count", "Code readability", "Algorithm time/space complexity", "Number of functions"], answer: 2 },
      { q: "Which keyword is used to declare a constant in JavaScript?", options: ["var", "let", "const", "fixed"], answer: 2 },
    ],
  },
  college: {
    label: "College Life", emoji: "🎓",
    questions: [
      { q: "What's commonly used to track unfinished course requirements?", options: ["Backlog", "Frontlog", "Sidelog", "Midlog"], answer: 0 },
      { q: "What is a 'viva' in college terms?", options: ["A party", "An oral exam", "A holiday", "A sports event"], answer: 1 },
      { q: "What do students usually pull before a deadline?", options: ["A prank", "An all-nighter", "A vacation", "A strike"], answer: 1 },
      { q: "What's the term for skipping class without permission?", options: ["Bunking", "Banking", "Blocking", "Booking"], answer: 0 },
      { q: "What event usually features cultural performances at college?", options: ["Orientation", "Cultural Fest", "Convocation", "Placement Drive"], answer: 1 },
      { q: "What's the common term for a senior student mentoring a junior?", options: ["Buddy", "Senior", "Mentor", "Captain"], answer: 2 },
      { q: "What's it called when you copy someone else's work and submit it as your own?", options: ["Referencing", "Plagiarism", "Paraphrasing", "Quoting"], answer: 1 },
      { q: "What is a 'backlog' in Indian college context?", options: ["An overdue assignment", "A failed exam to be cleared later", "A pending internship", "An elective subject"], answer: 1 },
      { q: "What is CGPA measured on in most Indian universities?", options: ["5-point scale", "10-point scale", "100-point scale", "4-point scale"], answer: 1 },
      { q: "What does 'GPA' stand for?", options: ["Grade Point Award", "Grade Point Average", "General Pass Assessment", "Grade Pass Award"], answer: 1 },
      { q: "What is 'ragging' in Indian college context?", options: ["A dance form", "Hazing / bullying by seniors", "A coding competition", "A study method"], answer: 1 },
      { q: "What document do students receive on completing their degree?", options: ["Marksheet", "Degree Certificate", "Transcript", "All of the above"], answer: 3 },
      { q: "What does 'internship' primarily help students gain?", options: ["Marks", "Friends", "Practical work experience", "Extra credits only"], answer: 2 },
      { q: "What is a 'seminar' in college?", options: ["A written test", "A presentation / lecture session", "A lab experiment", "A group project"], answer: 1 },
      { q: "Which app do most Indian college students use for group studies and class notes?", options: ["Telegram", "WhatsApp", "Discord", "All of the above"], answer: 3 },
      { q: "What's the minimum attendance percentage required in most Indian colleges?", options: ["50%", "60%", "75%", "90%"], answer: 2 },
      { q: "What is 'GATE' an entrance exam for?", options: ["Government jobs", "Postgraduate engineering admissions (M.Tech/PSUs)", "Medical colleges", "Law schools"], answer: 1 },
      { q: "What is the full form of 'HOD' in a college department?", options: ["Head Of Department", "Head Of Dean", "High Order Division", "Hour Of Duty"], answer: 0 },
    ],
  },
  memes: {
    label: "Memes", emoji: "😂",
    questions: [
      { q: "'Sus' is internet slang popularized by which game?", options: ["Fortnite", "Among Us", "Minecraft", "Roblox"], answer: 1 },
      { q: "What does 'NPC' stand for in meme culture?", options: ["New Player Character", "Non-Playable Character", "Next Path Choice", "No Personal Comment"], answer: 1 },
      { q: "'Stonks' is a meme about what going up?", options: ["Temperature", "Stocks", "Mood", "Height"], answer: 1 },
      { q: "What does 'rent free' mean when something lives in your head?", options: ["You forgot it", "You can't stop thinking about it", "It's expensive", "It's boring"], answer: 1 },
      { q: "'Touch grass' is internet slang telling someone to do what?", options: ["Garden", "Go outside / relax", "Mow the lawn", "Exercise more"], answer: 1 },
      { q: "What does 'W rizz' mean?", options: ["Winning at charisma", "A type of music", "A coding term", "A dance move"], answer: 0 },
      { q: "What does 'no cap' mean in Gen Z slang?", options: ["I'm joking", "No hat needed", "No lie / for real", "Don't yell"], answer: 2 },
      { q: "The 'This is Fine' meme shows a dog sitting in what?", options: ["Rain", "A flood", "A burning room", "A storm"], answer: 2 },
      { q: "What does 'lowkey' mean in internet slang?", options: ["Secretly / somewhat", "Very loudly", "Officially", "Never"], answer: 0 },
      { q: "The 'Distracted Boyfriend' meme template shows a man looking at who?", options: ["His boss", "Another woman while with his girlfriend", "A sports car", "A dog"], answer: 1 },
      { q: "What does 'POV' mean in meme / short video culture?", options: ["Point of View", "Part of Video", "Post Original View", "Proof Of Video"], answer: 0 },
      { q: "What is a 'Simp' in internet culture?", options: ["A simple person", "Someone overly attentive/submissive to impress someone", "A video game term", "A fitness goal"], answer: 1 },
      { q: "What does 'GOAT' stand for?", options: ["Greatest Of All Threats", "Greatest Of All Time", "Going Out At Twilight", "Game Over And Think"], answer: 1 },
      { q: "What does 'ratio' mean on Twitter/X?", options: ["Your follower count", "When replies outnumber likes (bad take)", "A photo format", "Retweet count"], answer: 1 },
      { q: "What does 'slay' mean in meme/Gen Z culture?", options: ["To lose badly", "To kill", "To do something impressively / look great", "To quit"], answer: 2 },
      { q: "What phrase does the 'Roll Safe' meme use?", options: ["Can't lose if you don't play", "Stay hydrated", "Nobody knows", "It be like that"], answer: 0 },
      { q: "What does 'ick' mean in dating slang?", options: ["Immediate attraction", "A sudden feeling of disgust/repulsion", "An inside joke", "Ignoring someone"], answer: 1 },
      { q: "What is a 'finsta'?", options: ["A fake/secondary private Instagram account", "A fitness Instagram", "A fan page", "Instagram for finance"], answer: 0 },
    ],
  },
};

export function getRandomQuestions(category = "general", count = 10) {
  const cat = TRIVIA_CATEGORIES[category] || TRIVIA_CATEGORIES.general;
  const pool = [...cat.questions];
  const safeCount = Math.min(count, pool.length);
  const result = [];
  for (let i = 0; i < safeCount; i++) {
    const idx = Math.floor(Math.random() * pool.length);
    result.push(pool.splice(idx, 1)[0]);
  }
  return result;
}
