// truthOrDareBank.js
// 4 tiers: casual → medium → advanced → insane (outrageous but safe, no 18+ content)

export const TOD_MODES = {
  casual: {
    label: "Casual", emoji: "🙂",
    desc: "Safe for siblings, coworkers, first hangouts",
    color: "#4ade80",
    truths: [
      "What's your most-used emoji?",
      "What's a food you pretend to like but secretly hate?",
      "What's your go-to karaoke song?",
      "What app do you spend the most time on?",
      "What's the last thing you Googled?",
      "What's your dream vacation spot?",
      "What's a skill you wish you had?",
      "What's your comfort show to rewatch?",
      "What's the weirdest food combo you actually enjoy?",
      "What's your most-used phrase or catchphrase?",
      "If you had a free day with no responsibilities, what would you do?",
      "What's a hobby you've always wanted to try?",
    ],
    dares: [
      "Do your best impression of a celebrity for 15 seconds.",
      "Talk in an accent for the next 2 rounds.",
      "Let the group pick your new profile picture for a day.",
      "Do 10 jumping jacks right now.",
      "Sing the chorus of your favorite song.",
      "Try to make everyone laugh in 20 seconds without touching anyone.",
      "Speak only in questions for the next 3 minutes.",
      "Do your best dance move for 10 seconds.",
      "Let someone draw a tiny doodle on your hand.",
      "Text a friend 'I just won a free pizza!' (no context).",
    ],
  },

  medium: {
    label: "Medium", emoji: "😏",
    desc: "More personal, more daring, still friendly",
    color: "#fbbf24",
    truths: [
      "What's a lie you've told that you still feel bad about?",
      "What's the most embarrassing thing in your search history?",
      "Who in this group would you trust with a secret first?",
      "What's a habit of yours that annoys people?",
      "What's the pettiest thing you've ever done?",
      "What's a rumor about you that was actually true?",
      "What's something you've never told your parents?",
      "What's the most awkward date you've been on?",
      "What's a text you regret sending?",
      "What's a nickname you hate being called?",
      "Who's the last person you stalked on social media?",
      "What's something you're insecure about but rarely admit?",

    ],
    dares: [
      "Let the group go through your camera roll for 30 seconds.",
      "Call a random contact and sing them happy birthday (even if it's not their birthday).",
      "Post 'I just learned something embarrassing about myself' with no explanation.",
      "Let the group write your next social media caption.",
      "Do an impression of someone in this room (friendly only).",
      "Reveal the last 3 emojis you sent and explain them.",
      "Let someone read your last 5 text messages out loud.",
      "Attempt to lick your elbow in front of everyone.",
      "Show your most recent selfie, no matter how bad.",
      "Text your last opened contact an completely random, out-of-context emoji",
    ],
  },

  advanced: {
    label: "Advanced", emoji: "🔥",
    desc: "Deep, vulnerable, ego on the line",
    color: "#f97316",
    truths: [
      "What's something you've never forgiven yourself for?",
      "Who do you compare yourself to the most, and why?",
      "What's the biggest risk you've never taken?",
      "What's a relationship (friend or partner) you regret ending — or not ending?",
      "What's something you pretend doesn't bother you, but it really does?",
      "What's a compliment you've never believed about yourself?",
      "What's something you're afraid people will find out about you?",
      "Who in this room do you think has misjudged you, and why?",
      "What's the last thing that made you cry alone?",
      "What's a decision you made out of fear, not love?",
      "What's something you want to say to someone here but haven't?",
      "If you could swap lives with someone in this room, who would it be and why?",
      "What is the most financially irresponsible thing you have done that you hide from everyone?",
      "What is the most illegal thing you have ever done without getting caught?",
      "Have you ever stolen something of high financial or sentimental value? What was it?",
      "What is the most compromising secret someone has on you that you would pay to keep quiet?",
  "If your life depended on betraying your best friend's biggest secret, would you do it?",
  "Who is your current crush/relationship?",
  "Who was your first crush?",
  "What's the most ridiculous thing you've done to impress someone?",
  "What's something you hope nobody ever finds out?",
  "Who was your most memorable or unexpected crush?",
  "Have you ever pretended to like a hobby just to impress someone you were interested in?",
    ],
    dares: [
      "Let the group ask you one question, brutally honest answer only, no dodging.",
      "Call someone right now and tell them one genuine thing you appreciate about them.",
      "Reveal your screen time report for this week, no excuses.",
      "Let someone in the group give you brutally honest feedback about your biggest weakness — and you can't react defensively.",
      "Describe yourself the way your harshest critic would.",
      "Tell the group the real reason behind your last breakup or falling out.",
      "Read your most recent journal/notes app entry out loud (skip if truly private, but pick a real one if you can).",
      "Let the group ask 'what's one thing you'd change about each of us' and answer honestly.",
      "Admit the last time you were jealous of someone in this room.",
      "Share a goal you're scared to say out loud because you might fail.",
      "Let the player to your right go through your internet search history for the past week.",
      "Let the person to your left send any text they want to anyone in your contacts.",
      "Hand over your unlocked phone to the group for three full minutes of free roaming.",
      "Put your phone on speakerphone and call a random fast-food place to complain about a fake issue.",
      "Open your banking app and show the entire group your exact current account balance.",
      "Call your most recent ex right now on speakerphone and say, 'I miss you, can we talk?' then mute and listen",
    ],
  },

  insane: {
    label: "Insane", emoji: "🌪️",
    desc: "Maximum chaos. Outrageous, savage, unfiltered — but always safe.",
    color: "#ef4444",
    truths: [
  "What's the most chaotic thing you've ever done?",
  "What's your most unhinged 3AM thought recently?",
  "What's your weirdest obsession?",
  "What's something you would never post online?",
  "What's the strangest dream you've ever had?",
  "What's the pettiest reason you've disliked someone?",
  "What's the weirdest thing you've Googled?",
  "What's your most irrational fear?",
  "What's your biggest social fail?",
  "What's a secret talent nobody expects?",
  "What's the craziest impulse decision you've made?",
  "What's something people think about you that's completely wrong?",
  "What's the most awkward situation you've ever been in?",
  "What's your biggest red flag?",
  "What's the funniest lie you've ever told?",
  "What's something you've pretended to understand but didn't?",
  "What's your weirdest habit?",
  "What's the most ridiculous thing you've spent money on?",
  "What's the strangest coincidence you've experienced?",
  "What's one thing you'd do if there were no consequences for 24 hours?",
  "What is the most illegal thing you have ever done without getting caught?",
  "If you had to cut one person in this room out of your life forever, who would it be?",
  "Have you ever actively sabotaged someone’s relationship, career, or reputation?",
  "What is the absolute biggest, most devastating lie you have ever told someone you love?",
  "If you could get away with a major crime and no one would ever know, what would you do?",
  "What is the most toxic, unforgivable thing you have thought about someone sitting in this room?",
  "What is the most compromising secret someone has on you that you would pay to keep quiet?",
  "Have you ever had crushes on two people at the same time? if yes who r them?",
  "Who in this room do you think has the most interesting secret?",
  "Have you ever pretended to like a hobby just to impress someone you were interested in?",
],
    dares: [
      "Let the group write a fake dramatic 'breaking news' headline about you and you must read it like a news anchor.",
      "Do a 30-second stand-up comedy bit roasting everyone in the room — no mercy, no apologies.",
      "Let the group pick an embarrassing nickname for you that you must respond to for the rest of the game.",
      "Re-enact your most embarrassing public moment as a dramatic movie scene.",
      "Speak in the most over-the-top dramatic soap-opera voice for the next 3 rounds.",
      "Let the group create a fake conspiracy theory about you and you must defend it as if it's true.",
      "Do your absolute worst attempt at the splits, a cartwheel, or any 'impressive' move and own the failure.",
      "Let someone do your makeup or hair blindfolded (or with their non-dominant hand) for 60 seconds.",
      "Give a fake dramatic award acceptance speech for 'Most Likely To [insert chaotic thing group picks]'.",
      "Let the group interview you like paparazzi, asking rapid-fire ridiculous questions you must answer in character.",
      "Call your crush or current romantic interest right now and confess your deepest feelings.",
      "Let the group look through your hidden, deleted, or archived photo albums right now.",
      "Put your phone on speaker and call your parents or a sibling to tell them you are getting married tomorrow.",
      "Let the person to your left send any text they want to anyone in your contacts.",
      "Hand over your unlocked phone to the group for three full minutes of free roaming.",
      "Let the group pick one person from your contact list and block them permanently.",
  "Let the group draft a highly controversial post and publish it to your main social media profile for 1 hour.",
  "Swap an article of clothing with the player across from you for the rest of the round.",
    ],
  },
};

export function getRandomPrompt(mode, type) {
  const list = TOD_MODES[mode][type === "truth" ? "truths" : "dares"];
  return list[Math.floor(Math.random() * list.length)];
}
